### ISSUE TITLE
There is no documentation on how to use OpenHeimer

### ISSUE THREAD

**Issue by Onako2** [ErrorNoInternet/OpenHeimer#1]
There is not documentation how to use openheimer
It would be useful to explain how to install/use it

**Comment by ErrorNoInternet** [comment]
Yea I'll probably do that after #2
I'll also provide pre-compiled binaries for those who don't want to set up a Go/Rust environment manually

#### But for now:

First you need to install the Go compiler (https://go.dev)
Then, compile the project using the `go build` command
Finally, run the `openheimer.exe` executable

Really easy.

And if you want custom flags, just pass them by using `openheimer.exe -flag value`

**Comment by Onako2** [comment]
Thanks for the fast reply!

**Comment by ErrorNoInternet** [comment]
Would still like to keep this open though, there is no clear documentation yet

**Comment by Onako2** [comment]
ok 👍

**Comment by flufferyomada** [comment]
What abt on a Linux Server?

**Comment by ErrorNoInternet** [comment]
Only thing that would be different is the file extension and Go installation method

e.g.

sudo pacman -S go
git clone ... && cd ...
go build
./openheimer

**Comment by PainfulPaladins** [comment]
Could I attempt to make a basic documentation? (Haven't done that before, would like to try this)

**Comment by Onako2** [comment]
> Could I attempt to make a basic documentation? (Haven't done that before, would like to try this)

Why not? It is always better to try than not to try

**Comment by PainfulPaladins** [comment]
For the download, should I list the binaries in the release or are they outdated?(will probably include how to build it too)

**Comment by ErrorNoInternet** [comment]
The binaries in the releases are from the `rust` (rewrite) branch, not the currently-working main branch. For that you have to compile it yourself.

**Comment by PainfulPaladins** [comment]
Oh my bad. I should probably make the documentation on the working branch then.

**Comment by PainfulPaladins** [comment]
started on #9
